export const LOAD_PROFILE = 'LOAD_PROFILE';
export const PHOTO_UPLOAD = 'PHOTO_UPLOAD';
export const ACCOUNT_INPUT = 'ACCOUNT_INPUT';
export const BILLING_ADDRESS_INPUT = 'BILLING_ADDRESS_INPUT';
export const BIRTHDAY_INPUT = 'BIRTHDAY_INPUT';
export const MOBILE_INPUT = 'MOBILE_INPUT';
export const CLICK_PROFILE_ITEM = 'CLICK_PROFILE_ITEM';
export const CLICK_BACK_BUTTON = 'CLICK_BACK_BUTTON';
